cat('Results started \n')
source('results1.R')
cat('Results1.R finished \n')
source('results2.R')
cat('Results2.R finished \n')
source('results3.R')
cat('Results3.R finished \n')
source('results4.R')
cat('Results4.R finished \n')
source('results5.R')
cat('Results5.R finished \n')
source('results6.R')
cat('Results6.R finished \n')
